<?php

/**
 * @file
 * Install and uninstall functions for deploy_steps module.
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function deploy_steps_install() {
  // Set default configuration values.
  $config = \Drupal::service('config.factory')->getEditable('deploy_steps.settings');
  $config->set('text', 'Default content to be displayed if JS is disabled.')->save();

  \Drupal::service('router.builder')->rebuild();
}

/**
 * Implements hook_uninstall().
 */
function deploy_steps_uninstall() {
  \Drupal::configFactory()->getEditable('deploy_steps.settings')->delete();
}
